disabled     = false
languageCode = "zh-cn"
languageName = "简体中文"
weight       = 4
title        = "Blowfish"


[params]
  displayName = "简体中文"
  isoCode     = "zh-cn"
  rtl         = false
  dateFormat  = "2006年01月02日"
  logo        = "img/blowfish_logo_transparent.png"
  description = "一个强大、轻量级的 Hugo 主题。"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "©2020-{ year } Oswald522. All Rights Reserved. "

  [params.author]
    name     = "Oswald522"
    image    = "img/blowfish_logo.png"
    headline = "记录个人生活，学习内容"
    # bio = ""
    links = [
      { email = "mailto:hello@chas5wasl@duck.com" },
      { github = "https://github.com/Oswald522" },
    ]
