disabled     = false
languageCode = "zh-cn"
languageName = "简体中文"
weight       = 15
title        = "Oswald's Blog"


[params]
  displayName = "简体中文"
  isoCode     = "zh-cn"
  rtl         = false
  dateFormat  = "2006/01/02"
  logo        = "img/blowfish_logo_transparent.png"
  description = "Oswald522 Blog. 以文字记录对抗遗忘"
  # secondaryLogo = "img/secondary-logo.png"
  copyright = "©2020-{ year } Oswald522. All Rights Reserved. "

  [params.author]
    name     = "Oswald522"
    image    = "img/logo.webp"
    headline = "记录个人生活，学习内容"
    # bio = ""
    links = [
      { email = "mailto:hello@chas5wasl@duck.com" },
      { github = "https://github.com/Oswald522" },
      { ocrid = "https://"}
    ]
