disabled = false
locale = "zh-cn"
label = "简体中文"
weight = 15
title = "云间散话"

# 参数配置
[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006/01/02"
logo = "img/blowfish_logo_transparent.png"
# secondaryLogo = "img/logo.png"  
description = "云间散话.以文字记录对抗遗忘|"
# secondaryLogo = "img/secondary-logo.png"
copyright = "©2020-{ year } Oswald522. All Rights Reserved. "

[params.author]
name = "云间散话 By Oswald"
image = "img/blowfish_logo.png"
email = "chas5wasl@duck.com"
headline = "捕捉生活光影&nbsp;定格日常瞬间&nbsp;留下人生足迹"


links = [
  { email = "mailto:hello@chas5wasl@duck.com" },
  { github = "https://github.com/oswald522" },
  { orcid = "https://orcid.org/0009-0008-5461-7440" },
  { rss = "https://blog.baos.eu.org/index.xml" },
  # { linuxdo = "https://linux.do/u/oswald522" },
  { mastodon = "https://mastodon.social/@oswald522" },
]
